#!/usr/bin/env bash

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running CardTest.php ***/"
./vendor/bin/phpunit --testdox tests/Unit/CardTest.php

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running DeckTest.php ***/"
./vendor/bin/phpunit --testdox tests/Unit/DeckTest.php

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running CardTest.php ***/"
./vendor/bin/phpunit --testdox tests/Unit/DealerTest.php --exclude skip

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running CardTest.php ***/"
./vendor/bin/phpunit --testdox tests/Unit/DealerTest.php --filter it_can_deal_cards_to_multiple_players_at_a_table

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running GamePlayTest.php ***/"
./vendor/bin/phpunit --testdox tests/Unit/GamePlayTest.php

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running HandIdentifierTest.php ***/"
./vendor/bin/phpunit --testdox tests/Unit/HandIdentifierTest.php

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running HandTypeTest.php ***/"
./vendor/bin/phpunit --testdox tests/Unit/HandTypeTest.php

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running TableSeatTest.php ***/"
./vendor/bin/phpunit --testdox tests/Unit/TableSeatTest.php

echo "/*** Running PotTest.php ***/"
./vendor/bin/phpunit --testdox tests/Unit/PotTest.php

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running PotHelperTest.php ***/"
./vendor/bin/phpunit --testdox tests/Unit/PotHelperTest.php

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running BetHelperTest.php ***/"
./vendor/bin/phpunit --testdox tests/Unit/BetHelperTest.php

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running GamePlayPotTest.php ***/"
./vendor/bin/phpunit --testdox  tests/Unit/GamePlayPotTest.php

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running ActionOptionsTest.php a_player_facing_a_bet_can_fold_call_or_raise ***/"
./vendor/bin/phpunit --testdox  tests/Unit/ActionOptionsTest.php --filter a_player_facing_a_bet_can_fold_call_or_raise

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running ActionOptionsTest.php a_player_facing_a_raise_can_fold_call_or_raise ***/"
./vendor/bin/phpunit --testdox  tests/Unit/ActionOptionsTest.php --filter a_player_facing_a_raise_can_fold_call_or_raise

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running ActionOptionsTest.php a_folded_player_has_no_options ***/"
./vendor/bin/phpunit --testdox  tests/Unit/ActionOptionsTest.php --filter a_folded_player_has_no_options

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running ActionOptionsTest.php the_big_blind_facing_a_call_can_fold_check_or_raise ***/"
./vendor/bin/phpunit --testdox  tests/Unit/ActionOptionsTest.php --filter the_big_blind_facing_a_call_can_fold_check_or_raise

echo '/*** REBUILDING DB ***/';
php application.php app:build-env
echo "/*** Running ActionOptionsTest.php a_player_facing_a_call_can_fold_call_or_raise ***/"
./vendor/bin/phpunit --testdox  tests/Unit/ActionOptionsTest.php --filter a_player_facing_a_call_can_fold_call_or_raise